// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ScraperJuridico.Infrastructure.Data;

#nullable disable

namespace ScraperJuridico.Infrastructure.Migrations
{
    [DbContext(typeof(ProcessoDbContext))]
    partial class ProcessoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ScraperJuridico.Domain.Entities.ParteProcesso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProcessoNumeroProcesso")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tribunal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProcessoNumeroProcesso", "Tribunal");

                    b.ToTable("Partes");
                });

            modelBuilder.Entity("ScraperJuridico.Domain.Entities.Processo", b =>
                {
                    b.Property<string>("NumeroProcesso")
                        .HasColumnType("text");

                    b.Property<string>("Tribunal")
                        .HasColumnType("text");

                    b.Property<string>("Assunto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Classe")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DataDistribuicao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DataUltimoAndamento")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Foro")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UltimoAndamento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("NumeroProcesso", "Tribunal");

                    b.ToTable("Processos");
                });

            modelBuilder.Entity("ScraperJuridico.Domain.Entities.ParteProcesso", b =>
                {
                    b.HasOne("ScraperJuridico.Domain.Entities.Processo", "Processo")
                        .WithMany("Partes")
                        .HasForeignKey("ProcessoNumeroProcesso", "Tribunal")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Processo");
                });

            modelBuilder.Entity("ScraperJuridico.Domain.Entities.Processo", b =>
                {
                    b.Navigation("Partes");
                });
#pragma warning restore 612, 618
        }
    }
}
